---
- name: check machines availability
  hosts: k8s
  become: no
  tags:
    - ping
  tasks:
  - name: ping task
    ping:

- name: Initially prepare VMs - all nodes
  hosts: k8s
  become: yes
  tags:
    - vmprep
  vars:
    ansible_become_password: "{{ansible_password}}"
  tasks:
    - name: Add IP address of all hosts to all hosts (sudo)
      lineinfile:
        dest: /etc/hosts
        regexp: '.*{{ item }}$'
        line: "{{ hostvars[item].ansible_host }} {{item}}"
        state: present
      when: hostvars[item].ansible_host is defined
      with_items: "{{ groups.all }}"

    - name: disable swap (sudo)
      ansible.builtin.shell: swapoff -a
      ignore_errors: true
    - name: remove swap from fstab (sudo)
      shell: sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

    - name: Create a directory for kernel modules (sudo)
      ansible.builtin.file:
        path: /etc/modules-load.d
        state: directory
        mode: '0755'
    - name: create containerd.conf to load modules (sudo)
      ansible.builtin.file:
        path: /etc/modules-load.d/containerd.conf
        state: touch
        mode: u=rw,g=r,o=r
    - name: Set up the IPV4 bridge (sudo)
      shell: echo 'overlay\nbr_netfilter' > /etc/modules-load.d/containerd.conf
    - name: Load the needed kernel modules (sudo)
      shell: modprobe -a overlay br_netfilter
    - name: create kubernetes.conf file (sudo)
      ansible.builtin.file:
        path: /etc/sysctl.d/kubernetes.conf
        state: touch
        mode: u=rw,g=r,o=r
    - name: change Kernel parameters (sudo)
      shell: echo 'net.bridge.bridge-nf-call-ip6tables = 1\nnet.bridge.bridge-nf-call-iptables = 1\nnet.ipv4.ip_forward = 1' > /etc/sysctl.d/kubernetes.conf
    - name: Reload the Kernel parameters (sudo)
      shell: sysctl --system

- name: Install docker and containerd - on all nodes
  hosts: k8s
  become: yes
  tags:
    - dockerinst
  vars:
    ansible_become_password: "{{ansible_password}}"
  tasks:
    - name: install containerd dependencies (sudo)
      ansible.builtin.apt:
        pkg:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - software-properties-common

    - name: fetch docker public GPG SigKey (sudo)
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmour -o /etc/apt/trusted.gpg.d/docker.gpg
    - name: add docker APT repository (sudo)
      shell: add-apt-repository -y "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

    - name: apt update (sudo)
      ansible.builtin.apt:
        update_cache: yes
    - name: install containerd (sudo)
      ansible.builtin.apt:
        name: containerd.io
        state: present
    - name: create containerd.conf to load modules (sudo)
      ansible.builtin.file:
        path: /etc/containerd
        state: directory
        mode: '0755'
    - name: containerd gen condif (sudo)
      shell: containerd config default | tee /etc/containerd/config.toml >/dev/null 2>&1
    - name: containerd use systemd as cgroup (sudo)
      shell: sed -i 's/SystemdCgroup \= false/SystemdCgroup \= true/g' /etc/containerd/config.toml
    - name: Restart and enable containerd service (sudo)
      ansible.builtin.service:
        name: containerd
        enabled: yes
        state: restarted

- name: prepare K8S tools - on all nodes
  hosts: k8s
  become: yes
  tags:
    - k8stools
  vars:
    ansible_become_password: "{{ansible_password}}"
  tasks:
    - name: add Kubernetes APT repo (sudo)
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
    - name: fetch K8S public GPG Signing Key (sudo)
      shell: curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key | gpg --dearmour -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    - name: add K8S APT repo (sudo)
      shell: echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /' > /etc/apt/sources.list.d/kubernetes.list

    - name: apt update(sudo)
      ansible.builtin.apt:
        update_cache: yes
    - name: Install Kubernetes Tools (sudo)
      ansible.builtin.apt:
        pkg:
        - kubelet
        - kubeadm
        - kubectl

    - name: hold package to prevent upgrade/removal (sudo)
      ansible.builtin.dpkg_selections:
        name: kubelet
        selection: hold
    - name: hold package to prevent upgrade/removal (sudo)
      ansible.builtin.dpkg_selections:
        name: kubeadm
        selection: hold
    - name: hold package to prevent upgrade/removal (sudo)
      ansible.builtin.dpkg_selections:
        name: kubectl
        selection: hold
    - name: enable kubelet (sudo)
      ansible.builtin.service:
        name: kubelet
        enabled: yes

- name: Start K8S cluster
  hosts: k8s
  become: yes
  vars:
    ansible_become_password: "{{ansible_password}}"
  tasks:
    - name: Init K8S control plane (sudo)
      when: "'k8s_master' in group_names"
      ansible.builtin.command:
        cmd: "kubeadm init --control-plane-endpoint={{ ansible_default_ipv4.address }}:6443 --pod-network-cidr=10.10.0.0/16"
    - name: create dir for k8s config (sudo)
      when: "'k8s_master' in group_names"
      ansible.builtin.file:
        path: "/home/{{ ansible_user }}/.kube"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'
    - name: Set up kubeconfig for regular user (sudo)
      when: "'k8s_master' in group_names"
      shell: "cp /etc/kubernetes/admin.conf /home/{{ ansible_user }}/.kube/config"
    - name: Change kubeconfig permissions (sudo)
      when: "'k8s_master' in group_names"
      ansible.builtin.file:
        path: "/home/{{ ansible_user }}/.kube/config"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'
    - name: Install Calico Network Plugin - CNI
      when: "'k8s_master' in group_names"
      become: no
      ansible.builtin.command:
        cmd: "kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml"
    - name: generate a new join token
      when: "'k8s_master' in group_names"
      become: no
      ansible.builtin.shell: "kubeadm token create --print-join-command"
      register: join_output

- name: Join K8S worker nodes to the Control Plane
  hosts: k8s_worker
  become: yes
  vars:
    ansible_become_password: "{{ansible_password}}"
  tasks:
    - name: Join worker nodes to the cluster (sudo)
      ansible.builtin.shell: "{{ hostvars[groups['k8s_master'].0]['join_output']['stdout'] }}"

