- name: start all vms (nodes for k8s)
  hosts: real_hosts
  become: no
  tasks:
    - name: Start all vms
      shell: vboxmanage startvm "{{item}}" --type headless && sleep 30
      loop:
        - vm1
        - vm2
        - vm3
        - vm4
        - vm11
        - vm12
      ignore_errors: true
