- name: clean entire installation
  hosts: k8s
  become: yes
  vars:
    ansible_become_password: "123"
  tasks:
  - name: Unhold kubelet (sudo)
    ansible.builtin.dpkg_selections:
      name: kubelet
      selection: install
  - name: Unhold kubeadm (sudo)
    ansible.builtin.dpkg_selections:
      name: kubeadm
      selection: install
  - name: Unhold kubectl (sudo)
    ansible.builtin.dpkg_selections:
      name: kubectl
      selection: install
  - name: disable kubelet (sudo)
    ansible.builtin.service:
      name: kubelet
      enabled: no

  - name: Remove Kubernetes Tools (sudo)
    ansible.builtin.apt:
      pkg:
      - kubelet
      - kubeadm
      - kubectl
      state: absent
  - name: remove K8S repository (sudo)
    ansible.builtin.file:
      path: /etc/apt/sources.list.d/kubernetes.list
      state: absent
  - name: remove containerd config (sudo)
    ansible.builtin.file:
      path: /etc/apt/keyrings
      state: absent

  - name: remove containerd config dir (sudo)
    ansible.builtin.file:
      path: /etc/containerd
      state: absent
  - name: Uninstall containerd package (sudo)
    ansible.builtin.apt:
      name: containerd.io
      state: absent

  - name: remove docker public GPG Signing Key (sudo)
    ansible.builtin.file:
      path: /etc/apt/trusted.gpg.d/docker.gpg
      state: absent
  - name: remove APT repo (sudo)
    ansible.builtin.file:
      path: /etc/apt/sources.list.d/docker.list
      state: absent

  - name: uninstall containerd dependencies (sudo)
    ansible.builtin.apt:
      pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - software-properties-common
      state: absent
