- name: poweroff all working vms
  hosts: k8s
  become: yes
  vars:
    ansible_become_password: "123"
  tasks:
    - name: Unconditionally shut down the machine with all defaults
      community.general.shutdown:
