apiVersion: v1
kind: Service
metadata:
  name: kube-foo-svc
  namespace: default
spec:
  type: NodePort
  selector:
    app: kube-foo-app
  ports:
    - port: 3001
      targetPort: 8001
      nodePort: 32001
      protocol: TCP

