apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-bar-app
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kube-bar-app
  template:
    metadata:
      labels:
        app: kube-bar-app
    spec:
      containers:
        - name: kube-bar-app
          image: hostick/bar:v1
          imagePullPolicy: Always
          ports:
          - containerPort: 8001
            protocol: TCP

