apiVersion: v1
kind: Service
metadata:
  name: kube-bar-svc
  namespace: default
spec:
  type: NodePort
  selector:
    app: kube-bar-app
  ports:
    - port: 80
      targetPort: 3002
      nodePort: 32002
      protocol: TCP

