apiVersion: v1
kind: Service
metadata:
  name: kube-foo-svc
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: kube-foo-app
  ports:
    - port: 80
      targetPort: 3001
      protocol: TCP

